runtime: python37

handlers:

- url: /Thanksgiving
  static_files: www/Thanksgiving/index.html
  upload: www/Thanksgiving/index.html

- url: /Thanksgiving/
  static_files: www/Thanksgiving/index.html
  upload: www/Thanksgiving/index.html

- url: /Thanksgiving(.*)
  static_files: www/Thanksgiving/\1
  upload: www/Thanksgiving/(.*)

- url: /Christmas
  static_files: www/Christmas/index.html
  upload: www/Christmas/index.html

- url: /Christmas(.*)
  static_files: www/Christmas/\1
  upload: www/Christmas/(.*)

- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)
